### ISSUE TITLE
unnecessary if statements

### ISSUE THREAD

**Issue by FireNinja7365** [Qiasfah/Null-Movement-Script#10]
i noticed a lot of the if statements are actually rather pointless and it may be the cause of #8
here is my version:
[Null Movement_Test.txt](https://github.com/user-attachments/files/16385469/Null.Movement_Test.txt)

**Comment by Qiasfah** [comment]
Well, if you aren't pressing the opposing key I don't see why you want to emit a key up of it. The if statements make it look like you actually released the other key first, if necessary.  I expect some games would be fine with excessive extra key up events, but there are impossible states without these ifs.  For example, an actual keyboard can't send two key ups of the same key without a key down in between.

**Comment by FireNinja7365** [comment]
that is fair, but when i was trying it it did seem more consistent than with the if statements, and i didn't have any issues like #8 did, but also i never had the issue originally so idk

edit: just tried it in apex and your version does have the issue of holding buttons, with mine it seems to happen less but it can still happen sometimes, but it also just seems to be an apex legends issue where it doesn't like really fast inputs

**Comment by Qiasfah** [comment]
In the key down event I was able to remove some if statements and maintain the expected keyboard states for the keys, perhaps that'll help the v2 script.

**Comment by FireNinja7365** [comment]
Alr, btw i tried the v1.1 script more and the bug still happens, it's just much less common, and it mainly seems to effect apex legends

**Comment by Qiasfah** [comment]
I think it's one big race condition between the key press event handlers if two keys are pressed at almost the same time

**Comment by FireNinja7365** [comment]
just made this version if you want to take a look

[Null Movement.txt](https://github.com/user-attachments/files/16397664/Null.Movement.txt)

**Comment by FireNinja7365** [comment]
did you ever look at that? ^
