### ISSUE TITLE
Script can no longer be used after the new update in cs2

### ISSUE THREAD

**Issue by ArinLP** [Qiasfah/Null-Movement-Script#12]
we all know that cs2 prevented the new razer keyboards from being able to snap tap, thus making this script unworkable, the script now kicks you out for input automation, the script used to work fine but now it can't be used, only with some bypass but I can't think of how that would work

**Comment by FireNinja7365** [comment]
We make simple code here brother, not anti-cheat bypasses

But.. You could probably just add a small, maybe randomized delay by a few milliseconds and then the game might not care as much, but that would also make the script less effective.

**Comment by Qiasfah** [comment]
Script is working as written, agreed on the point to not intentionally work-around Valves very clearly stated position here.
