### ISSUE TITLE
Small QOL suggestion

### ISSUE THREAD

**Issue by FireNinja7365** [Qiasfah/Null-Movement-Script#3]
it's not necessary but here are a few changes that i think would be nice:

#Requires AutoHotkey v1

screen_center_x := A_ScreenWidth/2
screen_center_y := A_ScreenHeight/2
ToolTip, Script Enabled,screen_center_x,screen_center_y
SetTimer, RemoveToolTip, -1000
return
RemoveToolTip:
ToolTip
return

End::
	MsgBox, 4,, Are you sure you want to exit?
        IfMsgBox Yes
            ExitApp

**Comment by Qiasfah** [comment]
I pulled in some changes and updated yesterday to AHK v2, I like the idea of having a QOL window though for closing the script, but I always just use the system tray AHK icon to close it. Can you update this for v2?

**Comment by FireNinja7365** [comment]
#Requires AutoHotkey v2

ToolTip "Script Enabled",A_ScreenWidth/2,A_ScreenHeight/2
SetTimer () => ToolTip(), -1000

End:: { ; <--- this button exits the script
	Result := MsgBox("Are you sure you want to exit?",, 4)
        if Result = "Yes" {
            ExitApp
	}
}

**Comment by FireNinja7365** [comment]
Also if you didn't know the #Requires AutoHotkey v2 actually tells the script which version to runin if you have both versions installed

**Comment by Qiasfah** [comment]
I've added it here: https://github.com/Qiasfah/Null-Movement-Script/commit/7c31f743074486a17b9e02464d5cb1a7d187c228

Commented out for the moment, I use the end key for things and am happy with just closing the script from the system tray, hopefully this is clear enough to users that if they want this feature they can just uncomment that block :)
