### ISSUE TITLE
support for non-QWERTY layouts using scancodes

### ISSUE THREAD

**Issue by WAZAAAAA0** [Qiasfah/Null-Movement-Script#6]
"WASD" doesn't exist in every keyboard layout. Besides rare schizo layouts like Dvorak or Colemak, the French are probably the most affected by bad software with their AZERTY layout.

To make the script universally compatible with all keyboards you can use the respective scancodes of the keys. Those would be:
```
W	SC011
A	SC01E
S	SC01F
D	SC020
```

random example script that uses scancodes (by pressing W it sends S):
```ahk
$*SC011::SC01F
```

AHKv1.1 script to print more scan codes just in case you need other keys:
```ahk
SetFormat, Integer, Hex
Gui +ToolWindow -SysMenu +AlwaysOnTop
Gui, Font, s14 Bold, Arial
Gui, Add, Text, w100 h33 vSC 0x201 +Border, {SC000}
Gui, Show,, % "// ScanCode //////////"
Loop 9
  OnMessage( 255+A_Index, "ScanCode" ) ; 0x100 to 0x108
Return

ScanCode( wParam, lParam ) {
 Clipboard := "SC" SubStr((((lParam>>16) & 0xFF)+0xF000),-2) 
 GuiControl,, SC, %Clipboard%
}
```

**Comment by Qiasfah** [comment]
Implemented: https://github.com/Qiasfah/Null-Movement-Script/commit/bda48f486ff533ed38d2dbf792cc8f6a5f9f4203
