### ISSUE TITLE
AHK wont open.

### ISSUE THREAD

**Issue by TheEmoBoy9887** [Qiasfah/Null-Movement-Script#7]
The AHK wont open. 
![image](https://github.com/user-attachments/assets/4c156179-8c26-4c2a-95a1-6757e5728f7e)
as u see its a problem in the code. eggoofficial on discord for more info

**Comment by FireNinja7365** [comment]
Are you running it withthe correct version of ahk? V1and v2 scripts are not compatible with eachother

**Comment by Qiasfah** [comment]
I've updated the script with a #requires statement!
