### ISSUE TITLE
small code compacting suggestion

### ISSUE THREAD

**Issue by FireNinja7365** [Qiasfah/Null-Movement-Script#9]
you can put all of the global variables in one line

replace these:
    global a_held
    global d_held
    global a_scrip
    global d_scrip

with this:
    global a_held,d_held,a_scrip,d_scrip

you can do the same thing for the S-W sections too

and at the start of the script where you declare the global variables you can just have this:
    global a_held,d_held,a_scrip,d_scrip,w_held,s_held,w_scrip,s_scrip := 0

**Comment by FireNinja7365** [comment]
nvm it causes some weird issues apparently

**Comment by Qiasfah** [comment]
Interesting syntax at least!

**Comment by FireNinja7365** [comment]
yeah, i thought it would work because it didn't give an error or anything but when i actually ran it it pooped itself

**Comment by jordanadania** [comment]
thats because this is AHK and not Java or C.
but my question is why are you re-declaring global variables inside of hotkeys? im almost certain thats not necessary whatsoever and doesnt even make sense logically.

**Comment by FireNinja7365** [comment]
> thats because this is AHK and not Java or C. but my question is why are you re-declaring global variables inside of hotkeys? im almost certain thats not necessary whatsoever and doesnt even make sense logically.

We re declare the globals because this is AHK and not java or C. 😀

**Comment by jordanadania** [comment]
I code in AHK, stuff much more complex than 2 keyboard presses. I've never had to declare globals in hotkeys.

**Comment by jordanadania** [comment]
Also I read the issues from this github, I don't think you know how to program.

**Comment by Qiasfah** [comment]
I'm not sure what you're on about, try it without the global definitions, you'll see it doesn't work.

V1 documentation: https://www.autohotkey.com/docs/v1/Functions.htm#Global
V2 documentation: https://www.autohotkey.com/docs/v2/Functions.htm#Global

**Comment by Qiasfah** [comment]
Though, looking again at the v2 documentation the "Assume-global mode" is interesting, could save 3 lines in each func by just doing a bare global rather than defining each variable as global.

**Comment by jordanadania** [comment]
Oops. My apologies. I thought the snarky reply was the owner.

I use global variables in some really complex code and I don't have to declare. I'm interested why your code doesn't work without them. I'd be willing to show you my code though it's pretty long.

Though it might be irrelevant to you if you only care about your code working or not. If you say it doesn't work then I believe you.

**Comment by Qiasfah** [comment]
I'd hazard a guess that you're only reading from the globals, not writing to them.

From the linked documentation: "Any variable reference in an [assume-local](https://www.autohotkey.com/docs/v2/Functions.htm#AssumeLocal) function may resolve to a global variable if it is only read. However, if a variable is used in an assignment or with the [reference operator (&)](https://www.autohotkey.com/docs/v2/Variables.htm#ref), it is automatically local by default."

Note how these functions update the value of the variables, and such need to be defined as global.

**Comment by jordanadania** [comment]
Nah I write to them. I even have an input from the user changing them.

I just sent you an invite to the code if you're interested.

**Comment by jordanadania** [comment]
In fact I have it so an input from the user changes the variables

**Comment by jordanadania** [comment]
I just nvited you to my code so you can see it.

**Comment by jordanadania** [comment]
I think you're right that I'm not writing to the variables. It looks like I use the variables to edit the code itself. Which wouldn't even work if it was an executable.

I will see myself out.

Sorry.
